version: '3'
services:
  flask_app_test:
    container_name: flask_app_test
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db_flask:5432/flask_db
    depends_on:
      - db_flask
  db_flask:
    container_name: db_flask
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flask_db
